// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRC6gS_rRwoTD40GnuZCzd7N0vuA2ld_o',
    appId: '1:705238699899:web:5a4d92c36be07eeb7fb7de',
    messagingSenderId: '705238699899',
    projectId: 'coinwallet-ab41c',
    authDomain: 'coinwallet-ab41c.firebaseapp.com',
    storageBucket: 'coinwallet-ab41c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hmy7Fq7KlcUxnegSkkoTr4XlvMrPQiE',
    appId: '1:705238699899:android:84aa80e1088c5ddb7fb7de',
    messagingSenderId: '705238699899',
    projectId: 'coinwallet-ab41c',
    storageBucket: 'coinwallet-ab41c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxFuA-B7N92KdXpY7utUMcNzARvZ-LR7Q',
    appId: '1:705238699899:ios:01604122cdb072d17fb7de',
    messagingSenderId: '705238699899',
    projectId: 'coinwallet-ab41c',
    storageBucket: 'coinwallet-ab41c.firebasestorage.app',
    iosBundleId: 'com.example.walletNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxFuA-B7N92KdXpY7utUMcNzARvZ-LR7Q',
    appId: '1:705238699899:ios:01604122cdb072d17fb7de',
    messagingSenderId: '705238699899',
    projectId: 'coinwallet-ab41c',
    storageBucket: 'coinwallet-ab41c.firebasestorage.app',
    iosBundleId: 'com.example.walletNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRC6gS_rRwoTD40GnuZCzd7N0vuA2ld_o',
    appId: '1:705238699899:web:bebd1abccb70df857fb7de',
    messagingSenderId: '705238699899',
    projectId: 'coinwallet-ab41c',
    authDomain: 'coinwallet-ab41c.firebaseapp.com',
    storageBucket: 'coinwallet-ab41c.firebasestorage.app',
  );

}